### ISSUE TITLE
can catalog's Caching*API cache persistently.

### ISSUE THREAD

**Issue by SimonGreenhill** [cldf/cldfbench#72]
Regenerating CLDF datasets is slow, mainly due to glottolog lookups. 

Most of the time we are building against a specific version (e.g. v4.4) so caching glottolog.langoids could easily be done, and could track version name or repos commit id. If the requested version or repos id was different the cache could be invalidated. 

CLDFbench already requires `appdirs` (although this doesn't appear to be used here) so it'd be easy to take advantage of `user_cache_dir` for this purpose.

**Comment by chrzyki** [comment]
Would the `--dev` flag be an option in your case? I.e. `cldfbench lexibank.makecldf lexibank_dataset.py --dev`?

**Comment by xrotwang** [comment]
The `--dev` flag is `pylexibank` specific. `cldfbench makecldf` does not have an equivalent.

I'm not sure caching `Glottolog.languoids()` would be really simple. Since we are dealing with somewhat complex python objects here, pickling might be the best option - but then the cache could also be `pyglottolog` version specific ...

**Comment by xrotwang** [comment]
From my experience with bigger CLDF datasets, the ~10sec loading of the Glottolog data is often dwarfed by long `cldf validate` runtimes. Also, caching initialized Python objects would mean using pickles - and as far as I can tell, this may lead to all kinds of hard-to-debug issues (e.g. if pickles are per-user, but are accessed by different versions of `pyglottolog` from various venvs ...).
