### ISSUE TITLE
Preferred way to insert comments

### ISSUE THREAD

**Issue by martino-vic** [cldf/cldfbench#79]
Hi everybody,

I hope this is the correct repo to open this issue:

I've realised there is an empty column "comments" in forms.csv -- I want to fill it but I'm hesitant to do so, knowing that it will be set to empty again the next time I'm running the lexibank script. I was thinking to add something like a "comments.csv" file to the raw folder or so, but it sounds a bit hacky and I was wondering if there might already exists a preferred way of doing this. Thanks in advance for the answer!

Best,

**Comment by xrotwang** [comment]
This is rather a `cldfbench`issue, because `cldfbench` is the tool to re-create CLDF data. The `cldfbench` paradigm to make data curation transparent is as follows:
- `raw/`: stores the data as received from the original source
- `cldf/`: stores the (possibly enriched) data in CLDF for re-use
- `etc/`: stores data contributed by the curators to enrich the original data (which is looked up during `makecldf`)

So your idea with a `comments.csv` is totally in line with `cldfbench`, and depending on whether you are the original creator of the data or whether you are creating a CLDF version of another dataset, this file would go into `raw` or `etc`.

**Comment by martino-vic** [comment]
Great, that's good to know! Thank you!
